# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  # keep vagrant from inserting insecure key
  config.ssh.insert_key=false
  
  # set the image for the vagrant box
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  ## Set the image version
  # config.vm.box_version = "15.2.31.247"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  
  # use own ssh key to provide to virtual box
  config.ssh.private_key_path = ["/home/jeriarch/.ssh/vagrant/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "/home/jeriarch/.ssh/vagrant/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
  end
end
