---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace:
    ? .Values.namespace: ~
    : ~
spec:
  replicas:
    ? .Values.replicas: ~
    : ~
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        tag: alpine
    spec:
      containers:
        - image: 'nginx:{{ .Values.tag }}'
          imagePullPolicy:
            ? .Values.PullPolicy: ~
            : ~
          name:
            ? .Values.repository: ~
            : ~
          resources:
            requests:
              cpu:
                ? .Values.cpu: ~
                : ~
              memory:
                ? .Values.memory: ~
                : ~
