apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
spec:
  ports:
    - port: '{ { int .Values.service.port } }'
      protocol: '{ { .Values.service.protocol } }'
      targetPort: '{ { int .Values.service.targetPort } }'
  selector:
    app: techtrends
  type: '{ { .Values.service.type } }'
